imports:
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    clusterId: '[Your TEST cluster ID]'
    orgId: '[Your TEST orgId]' # Azure Databricks only
    workspace:
      baseDir: '/__myproject__/{currentBranch}'