imports:
  - config.yaml

parameters:
  databricks:
    address: https://adb-776384709737263.3.azuredatabricks.net
    cluster_id: '0106-164555-acing965'
    workspace:
      base_dir: '/__myproject__/{current_branch}'
