imports:
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    clusterId: '0106-164555-acing965'
    orgId: '776384709737263' # Azure Databricks only
    workspace:
      baseDir: '/__myproject__/{currentBranch}'
