imports:
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    clusterId: '[Your DEV cluster ID]'
    orgId: '[Your DEV orgId]' # Azure Databricks only
    workspaceBaseDir: '/{currentBranch}' # Target path in Databricks workspace
