imports:
  - config.yaml

parameters:
  databricks:
    address: https://adb-1381789872102367.7.azuredatabricks.net
    cluster_id: '0215-134530-loxes449'
    org_id: '1381789872102367' # Azure Databricks only
    workspace:
      base_dir: '/__myproject__/{current_branch}'
