imports:
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    cluster_id: '[Your TEST cluster ID]'
    workspace:
      base_dir: '/__myproject__/{currentBranch}'